@extends('movie.create')

@section('id',$movie->id)
@section('putMethod', method_field('put'))
@section('mode','Edit')
@section('Title',$movie->Title)
@section('Format',$movie->Format)
@section('Length',$movie->Length)
@section('Year',$movie->Year)
@section('Rating1',($movie->Rating == 1) ? 'checked':null)
@section('Rating2',($movie->Rating == 2) ? 'checked':null)
@section('Rating3',($movie->Rating == 3) ? 'checked':null)
@section('Rating4',($movie->Rating == 4) ? 'checked':null)
@section('Rating5',($movie->Rating == 5) ? 'checked':null)
@section('FormatVHS',($movie->Format == 'VHS') ? 'selected':null)
@section('FormatDVD',($movie->Format == 'DVD') ? 'selected':null)
@section('FormatStreaming',($movie->Format == 'Streaming') ? 'selected':null)
