version: '2'
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - mysql
    command: ["/usr/local/bin/wait-for-mysql.sh", "laravel_mysql", "/usr/local/bin/init.sh"]
    volumes:
      - ./app:/app
    container_name: laravel_base
    ports:
      - "80:80"
    tty: true
  mysql:
    container_name: laravel_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dTRKn3JPWbAAxRE42uE3dkFaJOC7nuT9
      MYSQL_DATABASE: laravel_app
      MYSQL_USER: laravel_app_user
      MYSQL_PASSWORD: JGx05CWMKBmCWit7xfZjbrkYlMwX1b2F
